# Generated by Django 3.2.14 on 2022-07-24 02:55

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propiedades', '0001_initial'),
        ('zonas', '0003_alter_zona_tipo_zona'),
        ('agentes', '0004_alter_agente_redes_sociales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.IntegerField(choices=[(0, 'Creado por web'), (1, 'Tramitado por Operaciones'), (3, 'Finalizado'), (4, 'No interesa')], default=0)),
                ('nombre', models.CharField(blank=True, max_length=120, null=True)),
                ('apellido', models.CharField(blank=True, max_length=120, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Administración',
                'verbose_name_plural': 'Administraciones',
            },
        ),
        migrations.CreateModel(
            name='ContactoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.IntegerField(choices=[(0, 'Creado por web'), (1, 'Tramitado por Operaciones'), (3, 'Finalizado'), (4, 'No interesa')], default=0)),
                ('nombre', models.CharField(blank=True, max_length=120, null=True)),
                ('apellido', models.CharField(blank=True, max_length=120, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('ciudad', models.IntegerField(choices=[(0, 'Bogotá')], default=0)),
                ('curso', models.IntegerField(choices=[(0, 'Gestión Comercial y Estrategias Inmobiliarias')], default=0)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromotorCandidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.IntegerField(choices=[(0, 'Creado por web'), (1, 'Tramitado por Operaciones'), (3, 'Finalizado'), (4, 'No interesa')], default=0)),
                ('nombre', models.CharField(blank=True, max_length=120, null=True)),
                ('apellido', models.CharField(blank=True, max_length=120, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('ciudad', models.IntegerField(choices=[(0, 'Bogotá'), (1, 'Barranquilla'), (2, 'Otra')], default=0)),
                ('modo_trabajo', models.IntegerField(choices=[(0, 'Independiente'), (1, 'Trabajo con Inmobiliaria'), (2, 'Otro')], default=0)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zonas.municipio', verbose_name='Ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='ContactoPortales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_negocio', models.CharField(choices=[('arriendo', 'Arriendo'), ('compra', 'Compra'), ('no_interesa', 'No interesa')], max_length=32)),
                ('nombre', models.CharField(blank=True, max_length=120, null=True)),
                ('apellido', models.CharField(blank=True, max_length=120, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('medio_de_contacto', models.TextField(blank=True, null=True)),
                ('mensaje_usuario', models.TextField(blank=True, null=True)),
                ('ha_creado_sol_contacto', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('estado', models.IntegerField(choices=[(0, 'Creado por web'), (1, 'Requerimiento CREADO'), (3, 'Correo no aplica para requerimiento'), (4, 'No interesa')], default=0)),
                ('propiedad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='propiedades.propiedad')),
            ],
            options={
                'verbose_name': 'Contacto portales',
                'verbose_name_plural': 'Contacto portales',
            },
        ),
        migrations.CreateModel(
            name='ContactoPagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=120, null=True)),
                ('apellido', models.CharField(blank=True, max_length=120, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ha_creado_sol_contacto', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('estado', models.IntegerField(choices=[(0, 'Creado por web'), (1, 'Requerimiento CREADO'), (3, 'Correo no aplica para requerimiento'), (4, 'No interesa')], default=0)),
                ('propiedad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='propiedades.propiedad')),
            ],
        ),
        migrations.CreateModel(
            name='ContactoCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.IntegerField(choices=[(0, 'Creado por web'), (1, 'Tramitado'), (2, 'Finalizado'), (3, 'No interesa')], default=0)),
                ('nombre', models.CharField(blank=True, max_length=120, null=True)),
                ('apellido', models.CharField(blank=True, max_length=120, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('fecha_agenda', models.DateTimeField(blank=True, null=True)),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agentes.agente')),
                ('propiedad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='propiedades.propiedad')),
            ],
        ),
        migrations.CreateModel(
            name='Consignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.IntegerField(choices=[(0, 'Creado por web'), (1, 'Tramitado por Operaciones'), (3, 'Asignado a agente'), (4, 'No interesa'), (5, 'Cliente no acepta cond.')], default=0)),
                ('tipo_consignacion', models.IntegerField(choices=[(0, 'No determina'), (1, 'Arriendo'), (2, 'Venta'), (3, 'Otro')], default=0)),
                ('nombre', models.CharField(blank=True, max_length=120, null=True)),
                ('apellido', models.CharField(blank=True, max_length=120, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('precio_estimado', models.IntegerField(choices=[(0, '0 a $1.000.000'), (1, '$1.000.000 a $10.000.000'), (2, '$10.000.000 a $50.000.000'), (3, '$50.000.000 a $100.000.000')], default=0)),
                ('tipo_inmueble', models.IntegerField(choices=[(0, 'Casa'), (1, 'Apartamento'), (2, 'Oficina'), (3, 'Local'), (4, 'Bodega'), (5, 'Lote')], default=0)),
                ('zona', models.CharField(blank=True, max_length=120, null=True)),
                ('metraje', models.DecimalField(decimal_places=2, default=0, max_digits=17)),
                ('habitaciones', models.IntegerField(blank=True, default=0, null=True)),
                ('banos', models.IntegerField(blank=True, default=0, null=True)),
                ('garajes', models.IntegerField(blank=True, default=0, null=True)),
                ('agente', models.ForeignKey(limit_choices_to={'activo': True}, on_delete=django.db.models.deletion.CASCADE, to='agentes.agente')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consignaciones', to='zonas.municipio', verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': 'Consignación',
                'verbose_name_plural': 'Consignaciones',
            },
        ),
    ]
