# Generated by Django 3.2.14 on 2022-07-23 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['nombre'], 'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='municipio',
            options={'ordering': ['departamento', 'nombre'], 'verbose_name': 'Municipio', 'verbose_name_plural': 'Municipios'},
        ),
        migrations.AlterField(
            model_name='zona',
            name='tipo_zona',
            field=models.CharField(choices=[('pais', 'País'), ('ciudad', 'Ciudad'), ('upz', 'UPZ'), ('appto', 'Zona Dommun')], max_length=32),
        ),
    ]
