# Generated by Django 3.2.14 on 2022-07-23 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0002_auto_20220723_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zona',
            name='tipo_zona',
            field=models.CharField(choices=[('pais', 'País'), ('ciudad', 'Ciudad'), ('upz', 'UPZ'), ('dommun', 'Zona Dommun')], max_length=32),
        ),
    ]
