# Generated by Django 3.2.14 on 2022-07-23 23:19

import agentes.models
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zonas', '0002_auto_20220723_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='GestionDocumental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('documento_subido', models.FileField(blank=True, null=True, upload_to=agentes.models.upload_docs_gestion_documental)),
                ('categoria', models.IntegerField(choices=[(1, 'Documentos preconfigurados'), (2, '¿Cómo ser un agente ideal?')], default=1)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Gestión documental',
                'verbose_name_plural': 'Gestión documental',
            },
        ),
        migrations.CreateModel(
            name='PlanMembresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('precio_promocion', models.DecimalField(decimal_places=2, max_digits=17)),
                ('precio_fijo', models.DecimalField(decimal_places=2, max_digits=17)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Plan Membresía',
                'verbose_name_plural': 'Planes Membresía',
            },
        ),
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True)),
                ('nombre', models.CharField(blank=True, max_length=120, null=True)),
                ('apellido', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono_contacto', models.CharField(blank=True, max_length=80, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to=agentes.models.upload_foto_agente)),
                ('acepta_arriendo', models.BooleanField(default=True)),
                ('acepta_venta', models.BooleanField(default=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('publicado', models.BooleanField(default=True)),
                ('precio_arriendo_min', models.BigIntegerField(blank=True, default=1500000, null=True)),
                ('precio_venta_min', models.BigIntegerField(blank=True, default=250000000, null=True)),
                ('zonificacion', models.CharField(choices=[('bogota', 'Bogotá'), ('barranquilla', 'Barranquilla'), ('medellin', 'Medellín')], max_length=32)),
                ('redes_sociales', django.contrib.postgres.fields.jsonb.JSONField(default={'facebook': 'null', 'instagram': 'null'})),
                ('descripcion_perfil', models.FileField(blank=True, null=True, upload_to=agentes.models.upload_docs_agente)),
                ('numero_avaluo', models.IntegerField(default=0)),
                ('fecha_inicio_plan', models.DateTimeField(blank=True, null=True)),
                ('ciudades', models.ManyToManyField(blank=True, limit_choices_to={'tipo_zona': 'ciudad'}, to='zonas.Zona')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agentes', to='zonas.municipio', verbose_name='Ciudad')),
                ('plan_membresia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agentes', to='agentes.planmembresia', verbose_name='Plan')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agente', to=settings.AUTH_USER_MODEL, unique=True)),
                ('zonas_appto', models.ManyToManyField(blank=True, limit_choices_to={'tipo_zona': 'appto'}, related_name='zonas_appto', to='zonas.Zona')),
            ],
            options={
                'ordering': ('nombre', 'apellido'),
            },
        ),
    ]
