# Generated by Django 3.2.14 on 2022-07-23 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0003_alter_zona_tipo_zona'),
        ('agentes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agente',
            name='zonas_appto',
        ),
        migrations.AddField(
            model_name='agente',
            name='zonas_dommun',
            field=models.ManyToManyField(blank=True, limit_choices_to={'tipo_zona': 'dommun'}, related_name='zonas_dommun', to='zonas.Zona'),
        ),
    ]
