# Generated by Django 3.2.14 on 2022-07-24 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentes', '0003_alter_agente_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agente',
            name='redes_sociales',
            field=models.JSONField(default={'facebook': 'null', 'instagram': 'null'}),
        ),
    ]
