# Generated by Django 3.2.14 on 2022-07-24 02:16

from django.db import migrations, models
import django.db.models.deletion
import publicaciones.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agentes', '0004_alter_agente_redes_sociales'),
        ('propiedades', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_urgencia', models.CharField(choices=[('PPP', 'PPP'), ('PP', 'PP'), ('P', 'P')], default='P', max_length=32)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.IntegerField(choices=[(1, 'En Validación Fotos'), (0, 'En proceso SAB'), (2, 'Publicación NO CUMPLE'), (3, 'Publicado'), (4, 'Cerrado con Dommun'), (5, 'El cliente se arrepintió'), (6, 'El cliente cerró por otro medio'), (7, 'El broker decide no continuar'), (8, 'Cliente no aparece'), (9, 'Cliente pide cambio de broker'), (10, 'Duplicado'), (11, 'Despublicado')], default=3)),
                ('razon', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=17)),
                ('precio_admon', models.DecimalField(decimal_places=2, max_digits=17)),
                ('es_exclusivo', models.BooleanField(default=False)),
                ('certificado_lib_trad', models.FileField(blank=True, null=True, upload_to=publicaciones.models.upload_docs_propiedad)),
                ('contrato', models.FileField(blank=True, null=True, upload_to=publicaciones.models.upload_docs_propiedad)),
                ('publicado_portales', models.BooleanField(default=False)),
                ('confirmo_motivo', models.BooleanField(default=False)),
                ('bajo_precio', models.BooleanField(default=False)),
                ('visitas', models.IntegerField(blank=True, default=0, null=True)),
                ('agente', models.ForeignKey(limit_choices_to={'activo': True}, on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='agentes.agente')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_publicaciones.publicacion_set+', to='contenttypes.contenttype')),
                ('publicacion_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relacionada', to='publicaciones.publicacion')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='PublicacionVivienda',
            fields=[
                ('publicacion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publicaciones.publicacion')),
                ('tipo_negocio', models.CharField(choices=[('arriendo', 'Arriendo'), ('venta', 'Venta')], max_length=32)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='propiedades.vivienda')),
            ],
            options={
                'verbose_name': 'PublicacionVivienda',
                'verbose_name_plural': 'Publicaciones Viviendas',
            },
            bases=('publicaciones.publicacion',),
        ),
        migrations.CreateModel(
            name='PublicacionLotes',
            fields=[
                ('publicacion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publicaciones.publicacion')),
                ('tipo_negocio', models.CharField(choices=[('arriendo', 'Arriendo'), ('venta', 'Venta')], max_length=32)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='propiedades.lotes')),
            ],
            options={
                'verbose_name': 'PublicacionLotes',
                'verbose_name_plural': 'Publicaciones Lotes',
            },
            bases=('publicaciones.publicacion',),
        ),
        migrations.CreateModel(
            name='PublicacionIndustrial',
            fields=[
                ('publicacion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publicaciones.publicacion')),
                ('tipo_negocio', models.CharField(choices=[('arriendo', 'Arriendo'), ('venta', 'Venta')], max_length=32)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='propiedades.industrial')),
            ],
            options={
                'verbose_name': 'PublicacionIndustrial',
                'verbose_name_plural': 'Publicaciones Industriales',
            },
            bases=('publicaciones.publicacion',),
        ),
        migrations.CreateModel(
            name='PublicacionComercial',
            fields=[
                ('publicacion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publicaciones.publicacion')),
                ('tipo_negocio', models.CharField(choices=[('arriendo', 'Arriendo'), ('venta', 'Venta')], max_length=32)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='propiedades.comercial')),
            ],
            options={
                'verbose_name': 'PublicacionComercial',
                'verbose_name_plural': 'Publicaciones Comerciales',
            },
            bases=('publicaciones.publicacion',),
        ),
    ]
