# Generated by Django 3.2.14 on 2022-07-24 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=120, null=True)),
                ('apellido', models.CharField(blank=True, max_length=120, null=True)),
                ('nacionalidad', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('telefono_principal', models.CharField(max_length=32, null=True)),
                ('telefono_secundario', models.CharField(blank=True, max_length=32, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ('nombre', 'apellido'),
            },
        ),
        migrations.CreateModel(
            name='Necesidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_urgencia', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='C', max_length=32)),
                ('tipo_negocio', models.CharField(choices=[('arriendo', 'Arriendo'), ('compra', 'Compra'), ('venta', 'Venta')], max_length=32)),
                ('notas', models.TextField(blank=True, null=True)),
                ('precio_min', models.DecimalField(decimal_places=2, max_digits=17)),
                ('precio_max', models.DecimalField(decimal_places=2, max_digits=17)),
                ('area_min', models.DecimalField(decimal_places=2, max_digits=7)),
                ('area_max', models.DecimalField(decimal_places=2, max_digits=7)),
                ('habitaciones_min', models.IntegerField()),
                ('parqueaderos_min', models.IntegerField()),
                ('banos_min', models.IntegerField()),
                ('antiguedad_max', models.IntegerField(default=5)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Necesidad',
                'verbose_name_plural': 'Necesidades',
            },
        ),
        migrations.CreateModel(
            name='PropiedadNecesidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cita', models.DateTimeField(blank=True, null=True)),
                ('notas_cita', models.TextField(blank=True, null=True)),
                ('valor_propiedad_inicial', models.DecimalField(blank=True, decimal_places=2, max_digits=17, null=True)),
                ('valor_oferta', models.DecimalField(blank=True, decimal_places=2, max_digits=17, null=True)),
                ('valor_hipoteca', models.DecimalField(blank=True, decimal_places=2, max_digits=17, null=True)),
                ('valor_arras', models.DecimalField(blank=True, decimal_places=2, max_digits=17, null=True)),
                ('aseguradora', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('fecha_firma_promesa', models.DateTimeField(blank=True, null=True)),
                ('estado', models.IntegerField(choices=[(0, 'Agregado Manualmente'), (1, 'Enviado'), (2, 'Visita'), (3, 'Oferta'), (4, 'Cierre')], default=1, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('necesidad', models.ForeignKey(limit_choices_to={'activo': True}, on_delete=django.db.models.deletion.CASCADE, related_name='propiedades', to='clientes.necesidad')),
            ],
            options={
                'verbose_name': 'Propiedad vs Necesidad',
                'verbose_name_plural': 'Propiedades vs Necesidades',
            },
        ),
    ]
