# Generated by Django 3.2.14 on 2022-07-24 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propiedades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publicaciones', '0001_initial'),
        ('agentes', '0004_alter_agente_redes_sociales'),
        ('zonas', '0003_alter_zona_tipo_zona'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedadnecesidad',
            name='publicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicaciones.publicacionvivienda'),
        ),
        migrations.AddField(
            model_name='necesidad',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='necesidades', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='necesidad',
            name='propiedad_primer_contacto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='propiedades.propiedad'),
        ),
        migrations.AddField(
            model_name='necesidad',
            name='zonas',
            field=models.ManyToManyField(related_name='necesidades', to='zonas.Zona'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='agente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='agentes.agente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='propiedadnecesidad',
            unique_together={('necesidad', 'publicacion')},
        ),
    ]
